### ISSUE TITLE
KeyError: 'rboxes'

### ISSUE THREAD

**Issue by wangyanfu123** [dorbodwolf/GlidingVertexTrainer#2]
请问inference.py如何使用，我一直报错
(256,)
2020-04-14 18:48:01,906 maskrcnn_benchmark.utils.model_serialization INFO: rpn.head.conv.weight loaded from rpn.head.conv.weight of shape (256, 256, 3, 3)
torch.Size([3, 800, 1123])
Traceback (most recent call last):
File "tools/inference.py", line 233, in
main()
File "tools/inference.py", line 186, in main
rboxes = prediction.get_field( "rboxes" ).cpu()
File "/home2/Jc/gliding_vertex-master/maskrcnn_benchmark/structures/bounding_box.py", line 43, in get_field
return self.extra_fields[field]
KeyError: 'rboxes'
请问怎么解决

**Comment by scuizhibin** [comment]
我遇到的是AttributeError: module 'torchvision' has no attribute 'datasets'，不知道在呢没解决吗？

**Comment by scuizhibin** [comment]
AttributeError: module 'torchvision' has no attribute 'datasets'
不清楚怎么解决？很尴尬 。

**Comment by scuizhibin** [comment]
你这个问题我没有见过。

**Comment by wangyanfu123** [comment]
请问你训练自己的数据的时候在推理的时候是只有矩形框吗，我用的是faster rcnn 50fpn x1这个模型，然后在推理的时候预测的输出只有6个值，边框，类别，得分



---Original---

**Comment by scuizhibin** [comment]
对，我们的问题不一样。我的是没有datasets


---Original---

**Comment by scuizhibin** [comment]
请问你的环境和配置过程是什么的？可以讲一下吗？


---Original---
